### ISSUE TITLE
Factor out parameter error checking

### ISSUE THREAD

**Issue by sagadre** [mlfoundations/open_lm#107]
Currently parameter error checking and throwing is done on-the-fly in `main.py`. This means we may do some heavy weight initialization (e.g., of model) only to throw if a user passed incompatible flags. Having an error checking function, called after argparse, will alleviate this and also clean up code.

**Comment by IgorVasiljevic-TRI** [comment]
@achalddave looking into this

**Comment by achalddave** [comment]
#153 closes this
