### ISSUE TITLE
Revamp make_2048.py script

### ISSUE THREAD

**Issue by sagadre** [mlfoundations/open_lm#11]
Some ideas:
* add flags so that people can chunk to different chunk sizes. based on latest changes, people should chunk to the largest context length they expect to train on
* look into alternatives to a system call to `s3 cp`, perhaps using `fsspec` or `cloudpathlib`
* write directly to s3/cloud rather than caching locally and then pushing to cloud

**Comment by mitchellnw** [comment]
cc @revbucket who already did the revamp of this which exists (I believe)

**Comment by achalddave** [comment]
Given we have https://github.com/mlfoundations/open_lm/tree/main/open_lm/datapreprocess/ray now for tokenize+shuffle in place of make_2048, let's close this.
