### ISSUE TITLE
Add test for checkpoint loading after save

### ISSUE THREAD

**Issue by achalddave** [mlfoundations/open_lm#145]
We should add a test that:
1. trains a (small) model for a couple steps
2. saves it to disk
3. calls main() again with a path to the checkpoint on disk
4. trains a few steps

The test should test single process, DDP, and FSDP.

**Comment by jmercat** [comment]
I cannot assign this to myself but I can do it

**Comment by achalddave** [comment]
Closing this issue as we have added a test in #148, but @Vaishaal feel free to open a new issue if you reproduce the checkpoint loading bug you have
