### ISSUE TITLE
Import from attention.py error

### ISSUE THREAD

**Issue by sedrick-keh-tri** [mlfoundations/open_lm#202]
I can't seem to import from attention.py

`pip install git+https://github.com/mlfoundations/open_lm.git`

Stuff like these work without any issues:
`from open_lm.data import get_data`
`from open_lm.main import main`

It fails when I try to import from `open_lm.attention`
`from open_lm.attention import ATTN_ACTIVATIONS, ATTN_SEQ_SCALARS`
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ATTN_ACTIVATIONS' from 'open_lm.attention' (unknown location)
```

**Comment by sagadre** [comment]
hi @sedrick-keh-tri  what version of open_lm are you on? can you try `pip install -U git+https://github.com/mlfoundations/open_lm.git` in your environment?

**Comment by sedrick-keh-tri** [comment]
Hmm, I'm tried that and I'm on 0.0.27 but it still doesn't seem to be working. 

Anyways, I tried it on a ray environment and it worked there, so the issue is likely with my environment. Closing this issue.

**Comment by sedrick-keh-tri** [comment]
Seems like it was because I had a local open_lm on my PYTHONPATH
