### ISSUE TITLE
Add a fused RMSNorm operation

### ISSUE THREAD

**Issue by mitchellnw** [mlfoundations/open_lm#3]
Note the following helpful link we were sent: https://github.com/NVIDIA/apex/blob/bc4be41c6fdb889db84b9f61f35440f82a057948/apex/normalization/fused_layer_norm.py#L192

**Comment by Ryu1845** [comment]
Maybe use the xformers one? https://github.com/facebookresearch/xformers/blob/main/xformers/ops/rmsnorm.py#L72C11-L72C11

**Comment by ludwigschmidt** [comment]
Are we still planning to do this / where are we? @achalddave

**Comment by achalddave** [comment]
I believe @sagadre looked into a triton implementation (https://github.com/mlfoundations/open_lm/pull/40) but found it was slower than torch LayerNorm at small scales. I believe the only other implementation is in apex, and we don't want to add a dependency on it. 

For now, I think we're sticking with LayerNorm / LowPrecisionLayerNorm, but if we find a good fused RMSNorm implementation that can be pip installed, we can test it.

**Comment by achalddave** [comment]
Now that `--torchcompile` works using torch attention and torch implementation of swiglu, I don't think we need this. RMSNorm with torchcompile works about as fast as LayerNorm.
