### ISSUE TITLE
LLaMA weight loading

### ISSUE THREAD

**Issue by ludwigschmidt** [mlfoundations/open_lm#30]

**Comment by KnutJaegersberg** [comment]
I used a script I found in your github issues to convert the 1b model, but I don't know how to use it with hf transformers. 

https://huggingface.co/KnutJaegersberg/open_lm_1b

**Comment by mitchellnw** [comment]
see https://github.com/mlfoundations/open_lm/pull/33

**Comment by sagadre** [comment]
#39
