### ISSUE TITLE
Ablate on initialization

### ISSUE THREAD

**Issue by mitchellnw** [mlfoundations/open_lm#31]
interested in:

A) changing layer_id + 1 to args.num_layers.
B) removing the line std = std / math.sqrt(2 * (layer_id + 1))

**Comment by achalddave** [comment]
related: https://github.com/mlfoundations/open_lm/pull/225

**Comment by achalddave** [comment]
We tested #225 at 1B and it seems to hurt downstream evals significantly, unfortunately.
