### ISSUE TITLE
Problem in position embedding

### ISSUE THREAD

**Issue by jmercat** [mlfoundations/open_lm#4]
https://github.com/mlfoundations/open_lm/blob/619a8b3afcb4e0b0dda7fb58ed271a26662fc10f/open_lm/model.py#L129

It seems to me that the rotary position embedding is being applied on the head dimension (dim -2) of the vectors q, k instead of the sequence dimension (dim 1).
I think the head and sequence dimensions should be swapped before calling  position embedding .
(see https://github.com/facebookresearch/xformers/blob/748c159096d4f9fcfe3eaf22801e5aed4777210b/xformers/components/positional_embedding/rotary.py#L85)

What I'm proposing is simply to re-write RotaryWithCast as follow:
```python
class RotaryWithCast(RotaryEmbedding):
    def forward(self, q, k, v):
        q, k = super().forward(q.permute(0, 2, 1, 3), k.permute(0, 2, 1, 3))
        q = q.permute(0, 2, 1, 3)
        k = k.permute(0, 2, 1, 3)
        return q.to(v.dtype), k.to(v.dtype), v
```

**Comment by jmercat** [comment]
Here is the runs I made with a custom subset of starcoder data. The original 11m training is in brown. My implementation using a different positional encoding is in orange.
![Screenshot from 2023-08-31 10-22-09](https://github.com/mlfoundations/open_lm/assets/11698893/fe4ae6a0-0dcd-477c-877b-f8c2bbf40ab9)

**Comment by sagadre** [comment]
Good catch! The blow up curves your are seeing are similar to the ones we were seeing before we introduced qk norm for the smaller models. Will do some testing with this fix on my end as well. Would you like to open a PR?

**Comment by mitchellnw** [comment]
Wow, amazing catch! We really appreciate this.

**Comment by mitchellnw** [comment]
We've added your name to the README because this is a very substantial bug catch. It's pretty interesting that our first 1B/7B runs do pretty well even without proper posembeds, but we should fix this going forward.

**Comment by jmercat** [comment]
Great code base by the way. It's a pleasure to read.
Thanks for proposing to include me. I could open a PR but it's probably simpler for you to just include what I wrote (or a better version... I haven't tested if calling `contiguous` would make a difference).

**Comment by jmercat** [comment]
actually moving that line before the call to view would be enough... 

https://github.com/mlfoundations/open_lm/blob/9b3ca532bab801e7035ed7a3ff2f9771ed30ecd2/open_lm/model.py#L129

**Comment by sagadre** [comment]
The problem actually seems to be upstream in xformers. Opened an issue here: https://github.com/facebookresearch/xformers/issues/841
